### ISSUE TITLE
Cant connect to Project or cluster key not accepting  

### ISSUE THREAD

**Issue by darshana-danrox** [jdrumgoole/MongoDB-Atlas-API#3]
I have  given key details on the terminal and also try define as env variable  but none working 

Note : ip white listed 

```
$ echo $ATLAS_PUBLIC_KEY
SxxxxWxxxx
$ echo $ATLAS_PRIVATE_KEY
xc4xxxxxxxx-4xxxxx1-xxxxx-xxxxxxxx6xx
$ atlascli --publickey xxxxxxxxxu --privatekey fcx9xxxxxxxx-4xxxx1-8xxxx-4xxxxxx
```
```
Traceback (most recent call last):
  File "/usr/local/bin/atlascli", line 11, in <module>
    load_entry_point('mongodbatlas==0.2.3b2', 'console_scripts', 'atlascli')()
  File "/usr/local/lib/python3.7/site-packages/mongodbatlas-0.2.3b2-py3.7.egg/mongodbatlas/atlascli.py", line 192, in main
  File "/usr/local/lib/python3.7/site-packages/mongodbatlas-0.2.3b2-py3.7.egg/mongodbatlas/api.py", line 50, in get_this_organization
  File "/usr/local/lib/python3.7/site-packages/mongodbatlas-0.2.3b2-py3.7.egg/mongodbatlas/atlasorganization.py", line 9, in __init__
  File "/usr/local/lib/python3.7/site-packages/mongodbatlas-0.2.3b2-py3.7.egg/mongodbatlas/atlasresource.py", line 22, in __init__
  File "/usr/local/lib/python3.7/site-packages/mongodbatlas-0.2.3b2-py3.7.egg/mongodbatlas/apimixin.py", line 62, in __init__
  File "/usr/local/lib/python3.7/site-packages/mongodbatlas-0.2.3b2-py3.7.egg/mongodbatlas/atlaskey.py", line 35, in get_from_env
  File "/usr/local/lib/python3.7/site-packages/mongodbatlas-0.2.3b2-py3.7.egg/mongodbatlas/atlaskey.py", line 30, in getenv
 `mongodbatlas.errors.AtlasEnvironmentError: Private key environment variable 'ATLAS_PUBLIC_KEY' is not set`

**Comment by jdrumgoole** [comment]
I think this is working in the latest release. Can you give it another try? 

https://pypi.org/project/mongodbatlas/
